on: [push, pull_request]

name: Test

env:
  RUSTFLAGS: '-D warnings'

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

        include:
          # Test MSRV
          - rust: 1.31.0
            TARGET: x86_64-unknown-linux-gnu

          - rust: beta
            TARGET: x86_64-unknown-linux-gnu

          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        if: contains(matrix.TARGET, 'x86_64')
        with:
          command: test
          args: --target=${{ matrix.TARGET }}

      - name: Build examples
        uses: actions-rs/cargo@v1
        if: contains(matrix.TARGET, 'x86_64')
        with:
          command: build
          args: --target=${{ matrix.TARGET }} --examples
